### PR TITLE
Multiple fixes to get the foodie skill running under Alexa developer console

### PR DESCRIPTION
**Pull request by jimshalo10**
*Issue #1
@hyandell
*Description of changes:*
Fixes multiple files with missing libraries and non working intents .
The ASK-CLI page has been heavily updated as there were many documentation errors and IAM Role updates were missing, seen in my [link](https://github.com/jimshalo10/skill-sample-nodejs-the-foodie/blob/master/instructions/7-cli.md)

 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by SleepyDeveloper — COMMENTED** [review]
This passes the initial smell test. I’m unable to install and test at the moment. Once I get a moment to test, I’ll create a new lambda to test it.

**Comment by SleepyDeveloper** [comment]
This looks good, but I'm curious as to why you commented out the SuggestMealRecommendationIntentHandler. Without this handler it won't be able to suggest a meal once all the other slots have been filled. Once this has been added back, I can merge.

**Comment by SleepyDeveloper** [comment]
I found a few more issues with your changes. I haven't heard back so I've cloned your fork and I'm making the changes there. Once completed I'll push directly to this and close this PR. Thanks for all your help.

**Comment by jimshalo10** [comment]
Thanks it has been difficult to find time to start this again

**Pull request merged**
